dist: trusty
env:
  global:
    - GNARGSCOMMON='rtc_include_tests=false rtc_enable_protobuf=false use_custom_libcxx=false use_ozone=true rtc_include_pulse_audio=false' 
  matrix:
    - |
      GYP_GENERATOR_OUTPUT=x86_64     
      GNARGS='is_debug=false rtc_use_h264=true ffmpeg_branding="Chrome"'
      SYSROOT=${TRAVIS_BUILD_DIR}/webrtc/src/build/linux/debian_jessie_amd64-sysroot
#    - |
#      GYP_GENERATOR_OUTPUT=x86_64-debug     
#      GNARGS='is_debug=true rtc_use_h264=true ffmpeg_branding="Chrome"'
#      SYSROOT=${TRAVIS_BUILD_DIR}/webrtc/src/build/linux/debian_jessie_amd64-sysroot
    - |
      GYP_GENERATOR_OUTPUT=rpi-armv7  
      GNARGS='is_debug=false rtc_use_h264=true ffmpeg_branding="Chrome" is_clang=false target_cpu="arm" treat_warnings_as_errors=false' 
      CROSS=arm-linux-gnueabihf- 
      SYSROOT=${TRAVIS_BUILD_DIR}/webrtc/src/build/linux/debian_jessie_arm-sysroot GYP_DEFINES="target_arch=arm"
    - |
      GYP_GENERATOR_OUTPUT=rpi-armv6  
      GNARGS='is_debug=false is_clang=false target_cpu="arm" treat_warnings_as_errors=false arm_version=6 arm_arch="armv6" arm_float_abi="hard" arm_use_neon=false arm_optionally_use_neon=false rtc_build_with_neon=false arm_use_thumb=false rtc_include_opus=false use_sysroot=false' 
      CROSS=arm-linux-gnueabihf- 
      CFLAGS_EXTRA="-march=armv6 -mfpu=vfp -mfloat-abi=hard"
addons:
  apt:
    packages:
    - git
language: cpp
compiler:
- gcc
script:
# get toolchain
- git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git && export PATH=$PATH:$(pwd)/depot_tools
- if [ "$CROSS" == "arm-linux-gnueabihf-" ]; then git clone --depth 1 https://github.com/raspberrypi/tools.git rpi_tools && export PATH=$PATH:$(pwd)/rpi_tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin; fi
# get WebRTC
- mkdir webrtc
- pushd webrtc
- fetch --no-history --nohooks webrtc
# patch webrtc to not generate ninja files for examples (that depend on gtk)
- sed -i -e 's|"examples",||' src/BUILD.gn
# patch webrtc to not download chromium-webrtc-resources
- sed -i -e "s|'src/resources'],|'src/resources'],'condition':'rtc_include_tests==true',|" src/DEPS
- gclient sync
- popd
# get, build and install live555 & alsa
- make WEBRTCROOT=./webrtc live555 alsa-lib
- pushd webrtc
- pushd src
# build WebRTC
- gn gen ${GYP_GENERATOR_OUTPUT}/out/Release --args="${GNARGSCOMMON} ${GNARGS}"
- ninja -C ${GYP_GENERATOR_OUTPUT}/out/Release jsoncpp rtc_json webrtc
- popd
- popd
# build
- make WEBRTCROOT=./webrtc all tgz
# clean up
- rm -rf webrtc rpi_tools depot_tools
before_deploy:
- export RELEASE_PKG_FILE=$(ls *.tgz)
- echo "RELEASE_PKG_FILE=${RELEASE_PKG_FILE}"   
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: e2bfd2f4bf96f01d1a58a24a00901735c71cc852
  file: 
  - "${RELEASE_PKG_FILE}"
  on:
    repo: hoangnghiem205/webrtc-streamer-for-raspberry
    tags: true
